name: CI

on:
  push:
    branches: [ master ]
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests - ${{ matrix.ruby }} | ${{ matrix.gemfile }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ruby: "3.2", gemfile: gemfiles/rails_7_1.gemfile }
          - { ruby: "3.4", gemfile: gemfiles/rails_7_1.gemfile }
          - { ruby: "3.2", gemfile: gemfiles/rails_7_2.gemfile }
          - { ruby: "3.4", gemfile: gemfiles/rails_7_2.gemfile }
          - { ruby: "3.2", gemfile: gemfiles/rails_8_0.gemfile }
          - { ruby: "3.4", gemfile: gemfiles/rails_8_0.gemfile }
          - { ruby: "3.4", gemfile: gemfiles/rack.gemfile }
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup DB
        run: bundle exec rake db:setup
      - name: Run tests
        run: bundle exec rspec
